ADMIN_TELEGRAM_ID = 7478166001
ADMIN_PIN_HASH = "b94b543b6a3d9f52985763ffc974ee0bdf048e429ff7f7e8e394af413a08863"

# User States
USER_STATE_PENDING_APPROVAL = "PENDING_APPROVAL"
USER_STATE_ACTIVE = "ACTIVE"
USER_STATE_PAUSED = "PAUSED"
USER_STATE_SUSPENDED = "SUSPENDED"
USER_STATE_REJECTED = "REJECTED"
USER_STATE_TRADING_DISABLED = "TRADING_DISABLED"

# Setup Types for Signal Classification
SETUP_TREND_CONTINUATION = "TREND_CONTINUATION"
SETUP_TREND_PULLBACK = "TREND_PULLBACK"
SETUP_BREAKOUT_CONFIRMATION = "BREAKOUT_CONFIRMATION"
